version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_TOOL=${BUILD_TOOL:-webpack}  # Use webpack by default
    ports:
      - "80:80"
    restart: unless-stopped 